version: '3.8'

services:
  # 1. Backend Service
  
  backend:
    build: ./Backend  
    container_name: clinic-backend
    ports:
      - "8083:8083"
    # Neon 
    environment:
      
     
      - SPRING_PROFILES_ACTIVE=default

  # 2. Frontend Service 
  frontend:
    build: ./Frontend 
    container_name: clinic-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app         
      - /app/node_modules       
    depends_on:
      - backend

