spring.application.name=Clinic_Management_System
spring.datasource.url=jdbc:postgresql://ep-ancient-resonance-a1994qwn-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_AoeH32yUZWKB

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=clinicmanagementsystem3@gmail.com
spring.mail.password=akyn udqw imum mqnr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
